language: python
python:
  - "3.7"

env:
  - PLATFORMIO_PROJECT_DIR=tests/hc04
  - PLATFORMIO_PROJECT_DIR=tests/libs

install:
  - pip install -U https://github.com/OS-Q/S03/archive/master.zip
  - pio platform install https://github.com/OS-Q/P14.git

script:
  - pio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
